在Android的广播机制中，ActivityManagerService扮演着广播中心的角色，负责系统中所有广播的注册和发布操作。

a、注册广播接收器:在ContextWrapper类中借助ContextImpl类来实现：ContextWrapper.registerReceiver(xxx)

b、在ActivityManagerService中，广播的发送和处理是异步的，不等待广播接收器处理这些广播就返回了。
   广播消息发送的入口：ContextWrapper.sendBroadcast

c、Android应用程序发送广播的大致过程：
	1. 广播发送服务通过sendBroadcast把一个广播通过Binder(进程间通信)发送给ActivityManagerService，它根据广播的Action类型找到相应的广播接收器，然后把这个广播放进自己的消息队列中去；
    2. ActivityManagerService在消息循环中处理这个广播，并通过Binder(进程间通信)把这个广播分发给注册的广播接收分发器ReceiverDispatcher，ReceiverDispatcher把这个广播放进MainActivity所在的线程的消息队列中去
    3. ReceiverDispatcher的内部类Args在MainActivity所在的线程消息循环中处理这个广播，最终是将这个广播分发给所注册的BroadcastReceiver实例的onReceive函数进行处理。
	
ContextWrapper实现:frameworks/base/core/java/android/content/ContextWrapper.java